AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '**/*~'
    - 'vendor/**/*'
inherit_from:
  - https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/.rubocop_base.yml
  - .rubocop_todo.yml
Layout/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
